# template version 2021.4

version: '3.8'

services:
  build:
    image: python:3.10.0rc1-alpine3.14
    working_dir: /workspace
    entrypoint:
      - /bin/sh
      - build.sh
    volumes:
     - ./:/workspace
